### ISSUE TITLE
Error: @providesModule naming collision:   Duplicate module name: react-native-vector-icons

### ISSUE THREAD

**Issue by eduedix** [gaston23/react-native-twilio-video-webrtc#2]
in a fresh react-native project, I first install the package with:
`yarn add react-native-twilio-video-webrtc`

and then start the project with:
`react-native run-ios`

the build succeeds but the packager gives the following error:
```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/erdem/ShitApp/node_modules/react-native-twilio-video-webrtc/node_modules/react-native/local-cli/rnpm/core/test/fixtures/files/package.json collides with /Users/erdem/ShitApp/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/erdem/ShitApp/node_modules/react-native-twilio-video-webrtc/node_modules/react-native/local-cli/rnpm/core/test/fixtures/files/package.json collides with /Users/erdem/ShitApp/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/erdem/ShitApp/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:159:13)
    at p.getName.then.name (/Users/erdem/ShitApp/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:134:31)
~
Process terminated. Press <enter> to close the window
```

What can I do to resolve this problem?

**Comment by eduedix** [comment]
managed to fix this by doing
`rm -r node_modules/react-native-twilio-video-webrtc/node_modules`
